name: CI/CD Mini-Projet Cloud

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 3. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 4. Build and push Flask app image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mini-projet-cloud:latest

      - name: 5. Lancer docker-compose + Test
        run: |
          docker compose pull app
          docker compose up -d
          sleep 15
          curl -f http://localhost/tasks || (echo "API test failed" && exit 1)
          docker compose ps
          docker compose down
